DROP TABLE IF EXISTS person, book;
DROP TYPE IF EXISTS ROLE_ENUM;
DROP SEQUENCE IF EXISTS person_id_seq, book_id_seq;
CREATE TYPE ROLE_ENUM AS ENUM ('GUEST', 'USER', 'ADMIN');
CREATE TABLE person
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(30)  NOT NULL,
    surname    VARCHAR(30)  NOT NULL,
    year_birth INT          NOT NULL,
    CHECK (year_birth > 1850),
    email      VARCHAR(255) UNIQUE,
    address    VARCHAR(255) NOT NULL,
    role       ROLE_ENUM DEFAULT 'GUEST'
);
INSERT INTO
    person(name, year_birth, surname, email, address, role)
VALUES
    ( 'Иванов Иван Иванович', 1970, 'bosh', 'wewe@yandex.ru', 'Россия, Краснодар, 123456, ул. Партизан дом 5 кв 1'
    , 'GUEST')
  , ('Петров Петр Петрович', 1960, 'Aisbern', 'bestboy@i.ru', 'Россия, Москва, 125476, ул. Видова дом 2', 'ADMIN')
  , ('Алексеев Алексей Алексеевич', 1989, 'Brow', 'brow2341@mail.ru', 'USA, California, 230506, Wood street 7', 'GUEST')
  , ('Познер Владимир Владимирович', 1944, 'Dr', 'Dr-r@i.com', 'Parish, London, 134215, Elfi street 33', 'GUEST')
  , ( 'Федоров Мирон Янович', 1985, 'Smith', 'ol.123@rezolver.yu', 'Россия, Краснодар, 353000, ул. Партизан дом 3 кв 1'
    , 'USER')
  , ('JIMMY ', 2003, 'Boy', 'boyboyboy@boy.vok', 'Россия, Краснодар, 123324, ул. Партизан дом 1 кв 2', 'ADMIN');
CREATE TABLE book
(
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id INT REFERENCES person (id),
    title     VARCHAR(100)                         NOT NULL,
    author    VARCHAR(200)                         NOT NULL,
    year      INTEGER                              NOT NULL,
    CHECK (year < 10000),
    CHECK (year > 0)
);
INSERT INTO
    book(title, author, year)
VALUES
    ('Над пропастью во ржи', 'Джером Сэлинджер', 1951)
  , ('День опричника', 'Владимир Сорокин', 2006)
  , ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018)
  , ('Философия Java', 'Брюс Эккель', 2018)
  , ('Психопатология обыденной жизни', 'Фрейд Зигмунд', 1904)
--  , ('Игра в бисер', 'Герман Гессе', 1943)
--  , ('Бытие и время', 'Мартин Хайдеггер', 1927)
;
INSERT INTO
    book(person_id, title, author, year)
VALUES
    (1, 'Игра в бисер', 'Герман Гессе', 1943)
  , (2, 'Бытие и время', 'Мартин Хайдеггер', 1927);
